export const translations = {
  ko: {
    loading: '로딩중입니다...',
    fold_tab: '탭 접기',
    unfold_tab: '탭 펼치기',
    search: '검색',
    create_label: '라벨 생성',
    create_memo: '메모 추가',
    select_memos: '메모 선택',
    edit_label_name: '이름 변경',
    remove: '삭제',
    no_memo: '메모가 없습니다',
    label_name: '라벨 이름',
    save: '저장',
    cancel: '취소',
    enter_title: '제목을 입력해주세요',
    enter_content: '여기를 클릭하여 메모를 작성하세요',
    select_labels: '라벨 선택',
    delete_memo: '메모 삭제',
    create: '생성',
  },
  en: {
    loading: 'Loading...',
    fold_tab: 'Fold Tab',
    unfold_tab: 'Unfold Tab',
    search: 'Search',
    create_label: 'Create Label',
    create_memo: 'New Memo',
    select_memos: 'Select Memos',
    edit_label_name: 'Edit name',
    remove: 'Delete',
    no_memo: 'There is no memo',
    label_name: 'Label name',
    save: 'Save',
    cancel: 'Cancel',
    enter_title: 'Please enter the title',
    enter_content: 'Click here to write memo',
    select_labels: 'Select Labels',
    delete_memo: 'Delete Memo',
    create: 'Create',
  },
}